# docker-compose.yml

version: '3.8'

networks:
  my_first_project:
    name: my_first_project
    driver: bridge

services:
  fastapi:
    container_name : project_rk
    build: .
    # command: bash -c 'until nc -z postgres 5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/app
    ports:
      - 8001:8000
    environment:
      # - DATABASE_URL=postgresql://postgres:root123@db:5432/myproj
      - DATABASE_URL=postgresql+psycopg2://radhakrishnan_user:PfNSlVmjWwBthsT6EsxCWC9xcyNjsbBf@dpg-cgq0nr0u9tun42uokpb0-a:5432/radhakrishnan

      
    depends_on:
      - db
    networks:
      - my_first_project


  db:
    container_name : myfirstproject_postgres
    image: postgres
    volumes:
      - ./POSTGRES_DATA:/var/lib/postgresql@15/data/
    ports:
      - 5432
    environment:
      POSTGRES_DB: radhakrishnan
      POSTGRES_USER: radhakrishnan_user
      POSTGRES_PASSWORD: PfNSlVmjWwBthsT6EsxCWC9xcyNjsbBf
    networks:
      - my_first_project
